# Generated by Django 4.2.6 on 2025-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='行政区划代码')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('level', models.CharField(blank=True, choices=[('country', '国家'), ('province', '省份'), ('city', '市'), ('district', '区县')], default='', max_length=8, null=True, verbose_name='层级')),
                ('pcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属行政区划代码')),
                ('pname', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='所属行政区划名字')),
                ('fullname', models.CharField(blank=True, max_length=90, null=True, verbose_name='行政区划完整名字')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'db_table': 'area_code',
            },
        ),
    ]
